[client]
toolbarMode = "viewer"
showErrorDetails = false

[ui]
hideTopBar = true

[browser]
gatherUsageStats = false

[server]
enableXsrfProtection = false
enableCORS = false

[theme]
base = "dark"
primaryColor = "#bb86fc"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1f1f1f"
textColor = "#f5f5f5"
